# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.48
    has_acceleration_limits: true
    max_acceleration: 0.86
  joint_2:
    has_velocity_limits: true
    max_velocity: 0.48
    has_acceleration_limits: true
    max_acceleration: 0.43
  joint_3:
    has_velocity_limits: true
    max_velocity: 0.48
    has_acceleration_limits: true
    max_acceleration: 0.34
  joint_4:
    has_velocity_limits: true
    max_velocity: 0.76
    has_acceleration_limits: true
    max_acceleration: 0.86
  joint_5:
    has_velocity_limits: true
    max_velocity: 0.76
    has_acceleration_limits: true
    max_acceleration: 8.6
  joint_6:
    has_velocity_limits: true
    max_velocity: 1.52
    has_acceleration_limits: true
    max_acceleration: 8.6
  right_finger_bottom_joint:
    has_velocity_limits: true
    max_velocity: 1000.0
    has_acceleration_limits: false
    max_acceleration: 0.0
