# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    twist_controller:
      type: picknik_twist_controller/PicknikTwistController

    gen3_lite_gripper_controller:
      type: position_controllers/GripperActionController
      # type: joint_trajectory_controller/JointTrajectoryController

    fault_controller:
      type: picknik_reset_fault_controller/PicknikResetFaultController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
twist_controller:
  ros__parameters:
    joint: tcp
fault_controller:
  ros__parameters:
    joints:
      []

gen3_lite_gripper_controller:
  ros__parameters:
    joints:
      - right_finger_bottom_joint